apiVersion: v1
kind: Namespace
metadata:
  name: cc-ns

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc-dpl
  namespace: cc-ns
  labels:
    app: chittychat
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: chittychat
  template:
    metadata:
      name: chittychat
      namespace: cc-ns
      labels:
        app: chittychat
    spec:
      serviceAccount: cc-sa
      terminationGracePeriodSeconds: 30
      containers:
        - name: chittychat
          image: enricoboschi/chittychat:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
              name: chittychat

---

apiVersion: v1
kind: Service
metadata:
  name: cc-svc
  namespace: cc-ns
spec:
  selector:
    app: chittychat
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cc-ing
  namespace: cc-ns
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: cc.example.com
      http:
        paths:
          - pathType: Prefix
            path: "/ping"
            backend:
              service:
                name: cc-svc
                port:
                  number: 80