# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      jar_version: ${{ steps.version.outputs.jar_version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -q package

      - name: Setting up version
        id: version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Tagging docker image with ${VERSION}"
          echo "::set-output name=jar_version::${VERSION}"

      - name: Temporarily save jar artifact
        uses: actions/upload-artifact@v3
        with:
          name: app.jar
          path: ${{ github.workspace }}/main/target/chittychat-1.0.0.jar
          retention-days: 1
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: app.jar
      - name: Docker build
        run: |
          ls -a ${{ github.workspace }}
          echo "Docker build with tag: ${{ needs.build.outputs.jar_version }}"
          docker build --build-arg JAR=${{ needs.build.outputs.jar_version }} -t ${{ secrets.DOCKERHUB_USERNAME }}/chittychat:latest .

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Docker push
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/chittychat:${{needs.build.outputs.jar_version}}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/chittychat:latest
          docker-compose push
